#!/usr/bin/env node
// Generate the inline SVG icon sprite in src/index.html from icons.config.json.
//
// Each entry under "icons" maps a stable local id (used in the HTML as
// <use href="#ic-<id>">) to a Material Symbols name + FILL axis (0 = outline,
// 1 = filled). To swap an icon, change its "name"/"fill" here and regenerate —
// the id stays, so the HTML never needs editing.
//
// The drawings are fetched from the Material Symbols package on jsDelivr
// (latest, unless icons.config.json pins a version in "package"; the weekly
// workflow refreshes them and opens a PR on drift) and inlined as <symbol>s;
// the deployed site ships zero icon requests.
//
// Usage: node scripts/build-icons.mjs

import { readFile, writeFile } from "node:fs/promises";

const CONFIG = "icons.config.json";
const HTML = "src/index.html";
const START = "<!-- icons:start -->";
const END = "<!-- icons:end -->";

// Config values land in HTML ids and fetch URLs, so keep them to safe shapes.
const ID_RE = /^[a-z0-9-]+$/;
const NAME_RE = /^[a-z0-9_]+$/;

const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

async function fetchText(url) {
  let lastErr;
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const res = await fetch(url);
      if (res.ok) return await res.text();
      // A 404 means a bad icon name/fill in the config — fail fast, no retry.
      if (res.status === 404) throw new Error(`not found (404): ${url}`);
      lastErr = new Error(`HTTP ${res.status}: ${url}`);
    } catch (err) {
      lastErr = err;
      if (/404/.test(String(err.message))) throw err;
    }
    await new Promise((r) => setTimeout(r, 500 * (attempt + 1)));
  }
  throw lastErr;
}

async function main() {
  const cfg = JSON.parse(await readFile(CONFIG, "utf8"));
  const base = `https://cdn.jsdelivr.net/npm/${cfg.package}/${cfg.style}`;

  const symbols = [];
  for (const [id, { name, fill }] of Object.entries(cfg.icons)) {
    if (!ID_RE.test(id)) throw new Error(`invalid icon id "${id}" (must match ${ID_RE})`);
    if (!NAME_RE.test(name)) throw new Error(`invalid name "${name}" for icon "${id}" (must match ${NAME_RE})`);

    const file = fill ? `${name}-fill.svg` : `${name}.svg`;
    const svg = await fetchText(`${base}/${file}`);

    const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
    if (!viewBox) throw new Error(`no viewBox in ${file} (icon "${id}")`);

    // Keep only the inner drawing; drop fixed fill/size so it inherits
    // currentColor and the CSS-driven 1em box.
    const inner = svg
      .replace(/^[\s\S]*?<svg[^>]*>/, "")
      .replace(/<\/svg>\s*$/, "")
      .replace(/\s(?:fill|width|height)="[^"]*"/g, "")
      .trim();

    symbols.push(`      <symbol id="ic-${id}" viewBox="${viewBox}">${inner}</symbol>`);
    console.log(`  ic-${id}  <-  ${file}`);
  }

  const block = [
    START,
    "    <!-- Generated by scripts/build-icons.mjs — edit icons.config.json, not here. -->",
    '    <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false" class="icon-sprite">',
    ...symbols,
    "    </svg>",
    `    ${END}`,
  ].join("\n");

  let html = await readFile(HTML, "utf8");
  const re = new RegExp(`${escapeRe(START)}[\\s\\S]*?${escapeRe(END)}`);
  if (!re.test(html)) {
    throw new Error(`markers ${START} … ${END} not found in ${HTML}`);
  }
  html = html.replace(re, block);
  await writeFile(HTML, html);

  console.log(`\nWrote ${symbols.length} symbols into ${HTML}.`);
}

main().catch((err) => {
  console.error(`build-icons failed: ${err.message}`);
  process.exit(1);
});
